root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parserOptions:
  sourceType: module
ignorePatterns:
  - "src/typings/*"
rules:
  spaced-comment: error
  no-var: error
  no-extra-bind: error
  prefer-arrow-callback: error
  no-empty:
    - warn
    - allowEmptyCatch: true
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - vars: all
      args: none
      ignoreRestSiblings: true
      caughtErrors: none
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/array-type":
    - off
  "@typescript-eslint/no-var-requires": warn
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
      singleline:
        delimiter: semi
        requireLast: false
  "@typescript-eslint/explicit-module-boundary-types": off

env:
  node: true
