// https://github.com/Microsoft/vscode/issues/32813
export const ColorProps_Foreground = new Set<string>([])
export const ColorProps_Border = new Set<string>([])
export const ColorProps_Background = new Set<string>([
	"color",
	"outline-color",
	"border-color",
	"border-top-color",
	"border-right-color",
	"border-bottom-color",
	"border-left-color",
	"background-color",
	"text-decoration-color",
	"accent-color",
	"caret-color",
	"fill",
	"stroke",
	"stop-color",
	"column-rule-color",
	"--tw-ring-color",
	"--tw-ring-offset-color",
	"--tw-gradient-from",
	"--tw-gradient-to",
	"--tw-gradient-stops",
	"--tw-shadow-color",
])
export const ColorProps = new Set([...ColorProps_Foreground, ...ColorProps_Border, ...ColorProps_Background])

export const arbitraryClassnames: Record<string, string[]> = {
	"inset-": ["top", "right", "bottom", "left"],
	"inset-x-": ["left", "right"],
	"inset-y-": ["top", "bottom"],
	"top-": ["top"],
	"right-": ["right"],
	"bottom-": ["bottom"],
	"left-": ["left"],
	"z-": ["z-index"],
	"order-": ["order"],
	"grid-cols-": ["grid-template-columns"],
	"grid-rows-": ["grid-template-rows"],
	"auto-cols-": ["grid-auto-columns"],
	"auto-rows-": ["grid-auto-rows"],
	"col-": ["grid-column"],
	"row-": ["grid-row"],
	"columns-": ["columns"],
	"m-": ["margin"],
	"mt-": ["margin-top"],
	"mr-": ["margin-right"],
	"mb-": ["margin-buttom"],
	"ml-": ["margin-left"],
	"mx-": ["margin-left", "margin-right"],
	"my-": ["margin-top", "margin-bottm"],
	"space-x-": ["margin-left"],
	"space-y-": ["margin-top"],
	"p-": ["padding"],
	"pt-": ["padding-top"],
	"pr-": ["padding-right"],
	"pb-": ["padding-bottm"],
	"pl-": ["padding-left"],
	"px-": ["padding-left", "padding-right"],
	"py-": ["padding-top", "padding-bottm"],
	"aspect-": ["aspect-ratio"],
	"h-": ["height"],
	"w-": ["width"],
	"max-h-": ["max-height"],
	"min-h-": ["min-height"],
	"max-w-": ["max-width"],
	"min-w-": ["min-width"],
	"flex-": ["flex"],
	"flex-shrink-": ["flex-shrink"],
	"shrink-": ["flex-shrink"],
	"flex-grow-": ["flex-grow"],
	"grow-": ["flex-grow"],
	"basis-": ["flex-basis"],
	"gap-": ["gap"],
	"gap-x-": ["column-gap"],
	"gap-y-": ["row-gap"],
	"origin-": ["transform-origin"],
	"cursor-": ["cursor"],
	"scroll-m-": ["scroll-margin"],
	"scroll-mt-": ["scroll-margin-top"],
	"scroll-mr-": ["scroll-margin-right"],
	"scroll-mb-": ["scroll-margin-buttom"],
	"scroll-ml-": ["scroll-margin-left"],
	"scroll-mx-": ["scroll-margin-left", "scroll-margin-right"],
	"scroll-my-": ["scroll-margin-top", "scroll-margin-buttom"],
	"scroll-p-": ["scroll-padding"],
	"scroll-pt-": ["scroll-padding-top"],
	"scroll-pr-": ["scroll-padding-right"],
	"scroll-pb-": ["scroll-padding-bottm"],
	"scroll-pl-": ["scroll-padding-left"],
	"scroll-px-": ["scroll-padding-left", "scroll-padding-right"],
	"scroll-py-": ["scroll-padding-top", "scroll-padding-bottm"],
	"list-": ["list-style-type"],
	"rounded-": ["border-radius"],
	"rounded-bl-": ["border-bottom-left-radius"],
	"rounded-br-": ["border-bottom-right-radius"],
	"rounded-tl-": ["border-top-left-radius"],
	"rounded-tr-": ["border-top-right-radius"],
	"rounded-t-": ["border-top-left-radius", "border-top-right-radius"],
	"rounded-r-": ["border-top-right-radius", "border-bottom-right-radius"],
	"rounded-b-": ["border-bottom-left-radius", "border-bottom-right-radius"],
	"rounded-l-": ["border-top-left-radius", "border-bottom-left-radius"],
	"border-opacity-": ["opacity"],
	"border-": ["border-width", "border-color"],
	"border-t-": ["border-top-width", "border-top-color"],
	"border-r-": ["border-right-width", "border-right-color"],
	"border-b-": ["border-bottom-width", "border-bottom-color"],
	"border-l-": ["border-left-width", "border-left-color"],
	"border-x-": ["border-left-width", "border-right-width", "border-left-color", "border-right-color"],
	"border-y-": ["border-top-width", "border-bottom-width", "border-top-color", "border-bottom-color"],
	"divide-": ["border-color"],
	"divide-opacity-": ["opacity"],
	"divide-x-": ["border-left-width", "border-right-width"],
	"divide-y-": ["border-top-width", "border-bottom-width"],
	"bg-": ["background-color", "background-image", "background-position", "background-size"],
	"bg-opacity-": ["opacity"],
	"from-": ["background-color"],
	"via-": ["background-color"],
	"to-": ["background-color"],
	"object-": ["object-position"],
	"fill-": ["fill"],
	"stroke-": ["stroke", "stroke-width"],
	"text-": ["color", "font-size"],
	"text-opacity-": ["opacity"],
	"font-": ["font-family", "font-weight"],
	"leading-": ["line-height"],
	"tracking-": ["letter-spacing"],
	"decoration-": ["text-decoration-color", "text-decoration-thickness"],
	"underline-offset-": ["text-underline-offset"],
	"indent-": ["text-indent"],
	"placeholder-": ["color"],
	"placeholder-opacity-": ["opacity"],
	"caret-": ["caret-color"],
	"accent-": ["accent-color"],
	"ring-opacity-": ["opacity"],
	"ring-": ["padding", "color"],
	"ring-offset-": ["padding", "color"],
	"outline-": ["outline-width", "outline-color"],
	"outline-offset-": ["outline-offset"],
	"delay-": ["transition-delay"],
	"duration-": ["transition-duration"],
	"transition-": ["transition-property"],
	"ease-": ["transition-timing-function"],
	"will-change-": ["will-change"],
	"content-": ["content"],
	"animate-": ["animation"],
	"shadow-": ["box-shadow"],
	"drop-shadow-": ["box-shadow"],
	"translate-x-": ["padding"],
	"translate-y-": ["padding"],
	"rotate-": ["order"],
	"skew-x-": ["order"],
	"skew-y-": ["order"],
	"scale-": ["order"],
	"scale-x-": ["order"],
	"scale-y-": ["order"],
	"opacity-": ["opacity"],
	"blur-": ["padding"],
	"brightness-": ["order"],
	"contrast-": ["order"],
	"grayscale-": ["order"],
	"hue-rotate-": ["order"],
	"invert-": ["order"],
	"saturate-": ["order"],
	"sepia-": ["order"],
	"backdrop-opacity-": ["opacity"],
	"backdrop-blur-": ["padding"],
	"backdrop-brightness-": ["order"],
	"backdrop-contrast-": ["order"],
	"backdrop-grayscale-": ["order"],
	"backdrop-hue-rotate-": ["order"],
	"backdrop-invert-": ["order"],
	"backdrop-saturate-": ["order"],
	"backdrop-sepia-": ["order"],
	"border-spacing-": ["border-spacing"],
	"border-spacing-x-": ["border-spacing"],
	"border-spacing-y-": ["border-spacing"],
	// "<opacity>": ["opacity"],
	// "<number>": ["order"],
	// "<angle>": ["order"],
	// "<percentage>": ["order"],
	// "<length>": ["padding"],
}

export const deprecated = new Map<string, string>([
	["content", "The utility 'content' is now deprecated, remove it."],
	["overflow-ellipsis", "The utility 'overflow-ellipsis' is now deprecated, replace it with 'text-ellipsis'."],
	["flex-grow", "The utility 'flex-grow' is now deprecated, replace it with 'grow'."],
	["flex-grow-0", "The utility 'flex-grow-0' is now deprecated, replace it with 'grow-0'."],
	["flex-shrink", "The utility 'flex-shrink' is now deprecated, replace it with 'shrink'."],
	["flex-shrink-0", "The utility 'flex-shrink-0' is now deprecated, replace it with 'shrink-0'."],
	["decoration-slice", "The utility 'decoration-slice' is now deprecated, replace it with 'box-decoration-slice'."],
	["decoration-clone", "The utility 'decoration-clone' is now deprecated, replace it with 'box-decoration-clone'."],
])
