/* eslint-disable @typescript-eslint/no-explicit-any */
declare module "*.css"
declare module "*.less"
declare module "*.scss"
declare module "*.json"
declare module "*.yaml"
declare module "*.yml"
declare module "*.png"
declare module "*.jpg"
declare module "*.jpeg"
declare module "*.gif"
declare module "*.woff2"
